config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root 'welcome#index'

  get '/profile', to: 'profile#show'

  devise_for :user, :skip => [:sessions]

  as :user do
    get 'sign-in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign-in' => 'devise/sessions#create', :as => :user_session
    delete 'sign-out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # Account Settings
  devise_scope :user do
    get '/account', to: 'users/account#main'

    scope '/account' do
      get   '/profile-settings'  => 'users/account#profile_data', :as => :profile_settings
      patch '/profile-settings'  => 'users/account#profile_data'

      get   '/change-username' => 'users/account#change_username', :as => :change_username
      patch '/change-username' => 'users/account#change_username'
    end
  end

  if Rails.env.development?
    get '/error/not-found' => 'errors#file_not_found'
    get '/error/server' => 'errors#internal_server_error'
    get '/error/unprocessable' => 'errors#unprocessable'
  end
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_many :users
end

app/models/profile_data.rb
class ProfileData < ActiveRecord::Base
  belongs_to :user
  validates_date :birthday, :on_or_before => 13.years.ago, :allow_nil => true
end

app/models/user.rb
include Gravtastic

class User < ActiveRecord::Base
  has_one :profile_data, dependent: :destroy
  belongs_to :level
  after_create :after_create_handler

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :username, :presence => true, :uniqueness => true

  gravtastic :email, :secure => true, :default => :identicon

  private
    def after_create_handler
      ProfileData.create :user_id => self.id
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_for_unverified_account, if: :user_signed_in?

  protected

    def check_for_unverified_account
      if !current_user.confirmed_at
        flash.now[:alert] = 'You have not activated your account yet!'
      end
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end

    def require_sign_in
      if !user_signed_in?
        redirect_to new_user_session_path, alert: "You must be signed in to view that page!"
      end
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
    render :status => 404
  end

  def unprocessable
    render :status => 422
  end

  def internal_server_error
    render :status => 500
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :require_sign_in

   def show
    @user = current_user
  end
end

app/controllers/users/account_controller.rb
class Users::AccountController < DeviseController
  before_action :require_sign_in
  before_action :set_user_resource, :not => [:profile_data]

  layout 'account'

  def main

  end

  def profile_data
    self.resource = current_user.profile_data.clone

    if request.patch?
      resource.assign_attributes profile_data_params

      if resource.valid?
        resource.save!
        redirect_to profile_settings_path, notice: 'Your profile information has been saved.'
      end
    end
  end

  def change_username
    self.resource = current_user

    if request.patch?
      permitted = change_username_params

      if resource.valid_password? permitted[:password]
        resource.errors.add :password, 'is invalid.'
      end

      resource.assign_attributes :username => permitted[:username]

      if resource.valid? && resource.errors.empty?
        resource.save!
        redirect_to change_username_path, notice: 'Your username has been saved.'
      end
    end
  end

  private

    def set_user_resource
      self.resource = current_user
    end

    def profile_data_params
      params.require(:profile_data).permit(:hometown, :occupation, :birthday, :website, :interests)
    end

    def change_username_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="message message--errors">
      #{sentence}
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/account.html.erb
<% content_for :main do -%>
  <h1>My Account</h1>
  <section class="account__sidebar">
    <div class="account__sidebar__menu">
      <div class="account__sidebar__menu__header">My Account</div>
      <nav class="account__sidebar__menu__nav account_sidebar__menu__nav--active">
        <ul>
          <li><%= link_to "Account Overview", account_path %></li>
          <li><%= link_to "Update Track Record", root_path %></li>
          <li><%= link_to "Update Profile", profile_settings_path %></li>
          <li><%= link_to "Change Username", change_username_path %></li>
          <li><%= link_to "Change Email Address", root_path %></li>
          <li><%= link_to "Change Password", root_path %></li>
        </ul>
      </nav>
    </div>
  </section>
  <section class="account__main"><%= yield %></section>
  <div class="clear"></div>
<% end -%>

<%= render :file => 'layouts/base' %>

app/views/layouts/application.html.erb
<% content_for :main do -%>
  <%= yield %>
<% end -%>

<%= render :file => 'layouts/base' %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top Coasters - Experience the Top Thrill!</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>
  </head>
  <body id="<%= controller_name %>">
    <% if notice %><div id="flash__message__container"><p id="flash__message--notice"><%= notice %></p></div><% end %>
    <%= render 'layouts/parts/header' %>
    <div class="wrapper">
      <main>
        <% if alert %><p id="flash__message--alert"><%= alert %></p><% end %>
        <%= yield :main %>
      </main>
      <%= render 'layouts/parts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/parts/_footer.html.erb
<footer>
	<p>Top Coasters &mdash; Experience the Top Thrill!</p>
    <p>Created by <a href="http://www.alecgunnar.com/" target="_blank">Alec Carpenter</a></p>
</footer>

app/views/layouts/parts/_header.html.erb
<header class="header">
  <div class="wrapper">
    <div class="header__main-nav-drop" data-nav="main">Main Nav</div>
    <div class="header__member-nav-drop" data-nav="member">Member Nav</div>
    <div id="branding">
      <%= link_to 'Top Coasters Home', root_path %>
    </div>
    <section class="header__member-nav">
      <% if current_user %>
        <div class="member-nav__member">
          Welcome, <%= current_user.username %> <span class="member-nav__alert-count">0</span>
          <div class="member-nav__member__pop-down">
            <%= image_tag current_user.gravatar_url, :class => 'member-nav__profile-pic' %>
            <ul>
              <li><%= link_to "My Profile", profile_path %></li>
              <li><%= link_to "Account Settings", account_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
            <div class="clear"></div>
          </div>
        </div>
      <% else %>
        <ul class="header__member-nav--guest">
          <li><%= link_to "Create an Account", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        </ul>
      <% end %>
    </section>
  </div>
</header>
<nav class="nav__main">
  <div class="wrapper">
    <ul>
      <li><%= link_to 'Home', root_path, {id: 'nav__home'} %></li>
      <li><a href="/database">Database</a></li>
      <li><a href="/search">Search</a></li>
    </ul>
  </div>
</nav>

app/views/users/account/change_username.html.erb
<div id="profile_data">
  <h2>Change Username</h2>
  <%= error_messages! %>
  <div class="form__box">
    <%= form_for resource, :url => :change_username do |f| %>
      <div class="form__field">
        <%= label_tag 'New Username' %>
        <%= f.text_field :username %>
      </div>
      <div class="form__field">
        <%= label_tag 'Password' %>
        <%= f.password_field :password %>
      </div>
      <div class="form__submit">
        <%= f.submit 'Save Username' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/account/main.html.erb
<div id="overview">
  <h2>Account Overview</h2>
  <div class="message">
    <% if current_user.gravatar_url %>
      <div class="overview__profile-pic">
        <%= image_tag current_user.gravatar_url %>
      </div>
    <% end %>
    <div class="overview__account-info">
      <p><strong>Username:</strong> <%= current_user.username %></p>
      <p><strong>Account Level:</strong> <%= current_user.level.name %></p>
      <p><strong>Member Since:</strong> <%= l current_user.created_at, format: :date %></p>
    </div>
    <div class="clear"></div>
  </div>
  <p class="message text--center"><%= link_to "Update my Track Record", root_path %></p>
</div>

app/views/users/account/profile_data.html.erb
<div id="profile_data">
  <h2>Profile Settings</h2>
  <%= error_messages! %>
  <div class="form__box">
    <%= form_for resource, :url => :profile_settings do |f| %>
      <fieldset class="form__section">
        <h3 class="form__section__head">Profile Information</h3>
        <div class="form__field">
          <%= label_tag :hometown %>
          <%= f.text_field :hometown %>
        </div>
        <div class="form__field">
          <%= label_tag :occupation %>
          <%= f.text_field :occupation %>
        </div>
        <div class="form__field">
          <%= label_tag :birthday %>
          <%= f.date_select :birthday, include_blank: true, start_year: Time.now.year - 85, end_year: 13.years.ago.year, :order => [:month, :day, :year] %>
        </div>
        <div class="form__field">
          <%= label_tag :website %>
          <%= f.text_field :website %>
        </div>
        <div class="form__field">
          <%= label_tag :interests %>
          <%= f.text_field :interests %>
        </div>
      </fieldset>
      <div class="form__submit">
        <%= f.submit 'Save Profile Information' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/settings/main.html.erb
<div id="overview">
  <h2>Account Overview</h2>
  <div class="message">
    <% if current_user.profile_pic_url %>
      <div class="overview__profile-pic">
        <%= image_tag current_user.profile_pic_url %>
      </div>
    <% end %>
    <div class="overview__account-info">
      <h4><%= current_user.username %></h4>
      <p><strong>Account Level:</strong> Member</p>
      <p><strong>Member Since:</strong> <%= l current_user.created_at, format: :datetime %></p>
    </div>
    <div class="clear"></div>
  </div>
  <p class="message text--center"><%= link_to "Update my Track Record", root_path %></p>
</div>

app/views/welcome/index.html.erb
<div class="slideshow-wrapper">
  <div class="slideshow" id="slideshow">
    <ul class="slideshow__slides">
      <li class="slideshow__slide slideshow__slide--active slideshow__slide--voyage-holiday-world-lift-hill"><p>The Voyage at Holiday World</p></li>
      <li class="slideshow__slide slideshow__slide--dragster-cedar-point-winter-chillout"><p>Top Thrill Dragster at Cedar Point</p></li>
      <li class="slideshow__slide slideshow__slide--cheetah-hunt-busch-gardens-tampa-turn"><p>Cheetah Hunt at Busch Gardens Tampa</p></li>
      <li class="slideshow__slide slideshow__slide--kraken-seaworld-orlando-turning-to-diving"><p>Kraken at SeaWorld Orlando</p></li>
      <li class="slideshow__slide slideshow__slide--maverick-cedar-point-launched-lift"><p>Maverick at Cedar Point</p></li>
    </ul>
    <div class="slideshow__slide__text-background">&nbsp;</div>
  </div>
</div>

<script>
  $('#slideshow').slideshow({
    waitTime: 7500
  });
</script>

<div class="left">
  <h2 class="header--pretty">Amusement Today News Feed</h2>
</div>
<div class="right">
  <h2 class="header--pretty">Recent Posts</h2>
</div>
<div class="clear"></div>